// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugmlchfciufddnegcpgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbWxjaGZjaXVmZGRuZWdjcGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDM0MjMsImV4cCI6MjA3MTI3OTQyM30.v6e8E0yQyrrSU9zJ1IWjzqT4cCyP60H4wezAegudnw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});